static: static

# 数据库配置
db:
  - name: "sysbase"
    type: "sqlite"
    dsn: "file:sysbase.db?_auth&_auth_user=admin&_auth_pass=123456&_auth_crypt=sha256"
    max_open_conns: 100
    table_prefix: ""

install-k8s:
  source-dir: /data/installk8s